apiVersion: v1
kind: PersistentVolume
metadata:
 name: mongo-pv
 labels:
  type: local
spec:
 storageClassName: manual
 capacity:
  storage: {{.Values.db.volume.capacity}}
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: "/mnt/mongo_data"