apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: mongo-pv-claim
spec:
 storageClassName: manual
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: {{.Values.db.volume.capacity}}